name: Release artifacts

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and publish artifacts
        run: |
          npx conveyor -f ci.conveyor.conf make site
          npx conveyor -f ci.conveyor.conf make copied-site

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      CONVEYOR_AGREE_TO_LICENSE: 1
